'data_dir': './../../toxify/sequence_data/mlcb_data'
'pos_file_train': 'mlcb_1_pos_train.csv'
'neg_file_train': 'mlcb_1_neg_train.csv'
'pos_file_test': 'mlcb_1_pos_test.csv'
'neg_file_test': 'mlcb_1_neg_test.csv'
'window': 15
'maxLen' : 500
'N_units' : 150
'epochs': 50
'LR': 0.025
'only_predict' :  1
'saved_model_subdir' : False
